import {
  PiDropDuotone,
  PiCloudLightningDuotone,
  PiSquaresFourDuotone,
  PiToolboxDuotone,
  PiWarningDuotone,
  PiWindDuotone,
  PiShapesDuotone,
  PiCertificateDuotone,
  PiTrashDuotone,
  PiSealCheckDuotone,
  PiUmbrellaDuotone,
  PiArmchairDuotone,
  PiPaintBrushDuotone,
  PiClipboardTextDuotone,
  PiPlugDuotone,
  PiWrenchDuotone,
  PiLightbulbDuotone,
  PiMagnifyingGlassDuotone,
  PiLightningDuotone,
} from 'react-icons/pi';

export const SERVICE_ICONS = {
  leak: PiDropDuotone,
  storm: PiCloudLightningDuotone,
  shingle: PiSquaresFourDuotone,
  flashing: PiToolboxDuotone,
  sag: PiWarningDuotone,
  ice: PiWindDuotone,
  metal: PiShapesDuotone,
  material: PiCertificateDuotone,
  tearoff: PiTrashDuotone,
  ventilation: PiWindDuotone,
  warranty: PiSealCheckDuotone,
  patio: PiUmbrellaDuotone,
  living: PiArmchairDuotone,
  design: PiPaintBrushDuotone,
  permit: PiClipboardTextDuotone,
  panel: PiPlugDuotone,
  repair: PiWrenchDuotone,
  lighting: PiLightbulbDuotone,
  inspection: PiMagnifyingGlassDuotone,
  wiring: PiLightningDuotone,
};
